spring:
  application:
    name: api-solicitacoes

  datasource:
    url: jdbc:postgresql://localhost:5435/bd-solicitacoes
    username: coti
    password: coti
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mongodb:
    uri: mongodb://coti:coti@localhost:27018/bd-solicitacoes?authSource=admin&uuidRepresentation=standard

  rabbitmq:
    host: localhost
    port: 5672
    username: coti
    password: coti
    virtual-host: /

server:
  port: 8084